repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: conventional-commits
        name: Conventional Commits
        language: script
        entry: hooks/commit-msg
        stages: [commit-msg]
